version: "3.8"

services:
  app:
    build: .
    environment:
      VARIABLE1: "Merge de atributos usando docker override"
#    volumes:
#      - .:/usr/src
#      - /usr/src/node_modules
#    command: npx nodemon index.js

#  db:
#    image: mongo
